### ISSUE TITLE
Nom de l'application

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/dico-proso#1]
@Verronmere, valides-tu le nom de l'application suivant : **Hooz-hoo**  
L'idée est venue juste après ton départ, et il a semblé qu'il était plus pratique d'implémenter dès maintenant un nom d'application, plutôt que de le modifier plus tard.

**Comment by Verronmere** [comment]
Haha, c'est horrible. Alors, que ce soit le nom currant, après on pourra changer.
