### ISSUE TITLE
Création des modèles de données (SQLAlchemy)

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/dico-proso#14]
@Verronmere , je crée cette issue pour que nous puissions coordonner notre travail.  

Pour moi :  
- person
- authorship_person
- relation-type

Pour toi : 
- link
- authorship_link
- user (dans utilisateurs.py)

---

Ca te va ?

**Comment by Verronmere** [comment]
@alix-tz :)

**Comment by Verronmere** [comment]
J'ai fait mon partie de travail sur la branche issue14_user_link. Ce ne sera pas en conflict avec ta branche...

**Comment by Verronmere** [comment]
Il n'a rien ajouté m****e!

**Comment by alix-tz** [comment]
Si, car nous avons modifié le même fichier, ce n'est pas seulement une question de branche (elles sont mergées vers la même branche master à la fin).  

Si tu merges ma PR, tu peux mettre à jour ton repository, puis copier ce que tu as fait dans le fichier mis à jour.

**Comment by Verronmere** [comment]
C'est fait. Je ne comprend pas.

**Comment by vasaura** [comment]
En regardant les cours sur les jointures et si j'ai bien compris (mais ce n'est pas sur), j'ai repéré les choses suivantes: 
@alix-tz 
il me semble qu'il manque une jointure pour la classe Person : db.relationship avec la classe Link. 
pour l'attribut qui crée la jointure (dans Person), je pense qu'il vaut mieux prendre un autre nom, car "authorship_person" crée des confusions (comme dans "user" et "person" de la classe "Authorship_person"). on peut dire par exemple "authorships".
Pour la classe Relation_type je crois qu'il faut établir la db.relationship avec Link. 
pour la classe Authorship_person, je me demande si pour les ForeignKey, il ne faut pas plutôt 
authorship_person_user_id
authorship_person_person_id

@veronmere, il manque les db.relationship

De manière générale, je me demande si les attributs concernant les jointures ne devraient pas avoir d'autres noms que ceux des classes/tables car cela crée des confusions.  
C'est juste une idée. nous pouvons en discuter de tout ça.

**Comment by alix-tz** [comment]
Je ne vois pas la PR d'Ekaterina... 

Pour le lien entre Link et Person, c'est normal, nous sommes en train de mettre en comment et les liens entre les 3 tables que j'ai faites et les 3 tables d'Ekaterina doivent être faits.  

Je veux bien que nous parlions de vive voix de la question des noms des jointures car je ne comprends pas ce qui te pose problème... 

Merci pour tes remarques ! :)

**Comment by alix-tz** [comment]
@Verronmere il manque les "db.relationship" dans tes tables pour finaliser les jointures. 
Je vais ajouter ce qui manque et qu'a signalé Aurelia. 


Par contre pour continuer à ne travailler que sur une seule branche "pull request", tu peux m'envoyer ici ce que tu veux modifier. Je mettrai à jour le fichier modele.py

**Comment by alix-tz** [comment]
@Verronmere 
Avec l'aide de @vasaura , j'ai corrigé mes erreurs et fait correctement les jointures qui concernaient les tables sur lesquelles j'ai travaillé (j'en ai rajouté dans tes tables aussi, du coup). 
Il manque les jointures pour les classes "Authorship_link"-"link" et "Authorship_link"-"user".
