### ISSUE TITLE
Mock-ups pour création des pages

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/dico-proso#15]
Je rassemble ici toutes les photos données par Ekaterina de nos croquis préparatoires. 

# Modèles de pages

*Ici sont rassemblées les photos prises des mock-ups des pages de l'application.*

---

- **Accueil**

![20180220_163925](https://user-images.githubusercontent.com/33317799/37041548-c1f57318-215c-11e8-8596-cf068f52d7a0.jpg)

---

- **Page personne**  

![20180220_164718](https://user-images.githubusercontent.com/33317799/37041613-eba4b0a2-215c-11e8-94a0-664be0993e64.jpg)

*version révisée*

![20180220_165649](https://user-images.githubusercontent.com/33317799/37041637-fa255280-215c-11e8-9e66-bbc432b7071f.jpg)

---

- **Page index (tous les éléments de la base)**

![20180220_165027](https://user-images.githubusercontent.com/33317799/37041661-071a928e-215d-11e8-946e-c68a0e7fd451.jpg)

---

- **Page de résultat de recherche**

![20180220_170258](https://user-images.githubusercontent.com/33317799/37041687-0f12b750-215d-11e8-9c56-eaafe0daf3cc.jpg)

---

- **Page de connexion**

![20180220_165252](https://user-images.githubusercontent.com/33317799/37041700-1c10e918-215d-11e8-83ea-b6c2974af50b.jpg)

---

- **Page d'inscription**  

![20180220_165451](https://user-images.githubusercontent.com/33317799/37041812-5b200076-215d-11e8-8f25-fdf973b5e1c7.jpg)

--- 

**sur le même modèle de page de formulaire, il faudra aussi créer :**
- creation_personne.html
- creation_lien.html

**il nous aussi prévoir les pages de texte :**
- contact
- à propos

**Comment by alix-tz** [comment]
Comme on n'arrive pas à mettre ces photos dans le wiki, je ne crée pas une nouvelle issue mais j'ajoute les photos de nos tableaux préparatoires pour le projet en général : 

- **Définition du projet** 

![20180220_160438](https://user-images.githubusercontent.com/33317799/37042003-ca6fbd22-215d-11e8-859f-4d4d0386e727.jpg)

- **Réflexion sur le modèle de données**  

![20180220_162631](https://user-images.githubusercontent.com/33317799/37042026-def647de-215d-11e8-97c0-02be13a11bd8.jpg)

- **Organisation prévue du repository**

![20180220_172717](https://user-images.githubusercontent.com/33317799/37042051-ec684e44-215d-11e8-90f3-ecf251493c29.jpg)

**Comment by alix-tz** [comment]
Je me permets d'ajouter le mock up pour la page de création des liens.  
Après réflexion, faire les liens à partir des ID des personnes est la chose la plus simple. Mais pour améliorer l'expérience utilisateur, je vais ajouter quelque chose qui permet d'afficher le "nom prénom" de la personne rattachée à l'ID.  

Dans un deuxième temps, j'ajouterai aussi la possibilité de faire plusieurs liens en même temps.

![mockup_create_link](https://user-images.githubusercontent.com/33317799/37339082-cca8030e-26b9-11e8-954c-c20adae720f5.png)

**Comment by vasaura** [comment]
J'ai un doute et une question. Laquelle des pages de notre dossier template est la page consacrée à la notice de la personne? j'ai l'impression qu'elle n'existe pas encore, n'est-ce pas?

**Comment by vasaura** [comment]
un schéma avec du crayon et papier avec les principaux champs de la notice de la personne 
![img_0350](https://user-images.githubusercontent.com/33260954/37523544-f21bcfbc-292f-11e8-8b61-8c073527f4fc.JPG)

**Comment by alix-tz** [comment]
@vasaura 
Tu as raison, il n'y a pas le fichier html pour la page de notice de personne. J'ai oublié de la lister !

**Comment by vasaura** [comment]
pas de problème. merci pour la confirmation. je comptais la créer
