### ISSUE TITLE
Répartition des pages

### ISSUE THREAD

**Issue by eglantinecharmetant** [Chartes-TNAH/dico-proso#20]
Suite à notre réunion, nous avons décidé de nous répartir les pages du site de la manière suivante : 

- Page accueil : @lduflos [FAIT]
- Notice personne : @vasaura (et @lduflos  cf. creation personne) [FAIT]
- Page index : @vasaura [FAIT]
- Page résultat de recherche : @lduflos [FAIT]
- Page connexion : @Verronmere [FAIT]
- Page inscription : @eglantinecharmetant [FAIT]
- Page création personne : @lduflos [FAIT]
- Page création de lien : @alix-tz  [FAIT]
- Page contact : @alix-tz *(edit)* [FAIT]
- Page à propos : @alix-tz  [FAIT]
- Page modification personne @vasaura [FAIT]
- Page modification lien @alix-tz [FAIT]
- Page suppression personne @vasaura [FAIT]
- Page suppression lien @alix-tz [FAIT]

**Comment by alix-tz** [comment]
Merci !

**Comment by alix-tz** [comment]
Pour rappel, la création des pages inclue de préparer la partie "route" et la partie "template". 
C'est @lduflos qui s'occupe aussi du *container*.

**Comment by alix-tz** [comment]
Dites, on va avoir des gros risques de conflits pour le fichier "routes.py". Comment pensez-vous qu'on peut s'y prendre pour les éviter ? Travailler chacune sur un fichier "route_prenom" puis tout rassembler ensuite ?

**Comment by vasaura** [comment]
ta proposition me parait très bien: créer un fichier route_prenom

Au sujet des pages, j'ai un doute sur l'utilité d'une page entière pour contact. on pourrait mettre le contact dans la page "à propos", non? 

Si tout le monde est d'accord avec cette solution, je vais travailler en binom avec @Verronmere  sur la page personne (la notice).

**Comment by eglantinecharmetant** [comment]
Je suis d'accord avec toi @alix-tz  pour le fichier route_prenom!

**Comment by lduflos** [comment]
Je suis d'accord pour les fichiers routes

**Comment by lduflos** [comment]
Je viens de faire une PR avec le conteneur et les metadata.
Voici un visuel de la page conteneur, qu'il est bien évidemment possible de modifier selon vos envies ;)
![capture du 2018-03-12 10-49-52](https://user-images.githubusercontent.com/33370304/37281550-b72d621c-25f1-11e8-9427-2036aaaefdd9.png)
Pour info, dans le dossier "partials" des templates, il y a aussi un fichier "recherche" en html que je n'ai pas encore eu le temps de faire et que je me propose de faire car il est en lien avec la page d'accueil

**Comment by alix-tz** [comment]
Merci Léa pour ce conteneur tout beau tout propre et pas noir ! :+1:  
Je m'occupe de faire un petit logo, pour personnaliser encore un peu plus l'application.  

A-t-on réellement besoin de la page "recherche" et du fichier qui va avec ? 

Si on a le temps à un moment, 2 remarques sur la mise en page : 
- il faudrait espacer les 3 éléments du footer
- on n'a pas besoin de "rechercher" dans le bouton de recherche
Mais c'est vraiment des détails !

**Comment by alix-tz** [comment]
@vasaura , dans ce cas je récupère aussi la création de la partie "contact".

**Comment by lduflos** [comment]
Pour le moment je n'ai pas travaillé le footer car on avait émis l'idée d'y insérer un formulaire contact rapide. Je peux enlever le mot "recherche" dans le bouton si vous préférez.

Concernant la page html recherche pour moi, cela correspond en fait au formulaire de recherche avancée (volet droit sur la page d'accueil) #15, mais peut être n'est-ce pas pertinent de le dissocier de la page d'accueil

**Comment by Verronmere** [comment]
Quelqu'une a dit que page contatc était sans intérêt? Je pense que c'est vrai pour l'instant. Alors , on n va pas envoyer des branches avec nos pages une par une (la dernière fois on m'a dit qu'il ne fallait pas faire des choses comme ça)? On les cole alors? Pour ma part je dis que j'ai presque rien changé sur les exemples de gazeteer.

**Comment by alix-tz** [comment]
Si tu lis la conversation ici @Verronmere , Aurélia a évoqué le fait que la page contact pouvait être mise avec la page "à propos".  C'est la raison pour laquelle j'ai mofidié le message initial d'Eglantine.  

Mais j'ai aussi évoqué le fait qu'on pouvait se passer de faire une page "contact" en créant simplement un "pop-up" en javascript, qui contiendrait un formulaire de contact ou simplement les informations de contact (par exemple : l'adresse de l'école).  
En ce qui me concerne, je ne pense pas que "contact" et "à propos" doivent être rassemblés.

**Comment by alix-tz** [comment]
J'ajoute dans la liste initiale des pages plusieurs éléments que nous avons oubliés.

**Comment by lduflos** [comment]
En regardant les PR pour les inscriptions utilisateurs, je me suis aperçue que nous n'avons pas pensé à prévoir une page de modification des données utilisateurs, ou peut-être ai-je loupé un passage ?

**Comment by vasaura** [comment]
Oui, tu as raison, nous n'avons pas prévue de page pour modifier les données des utilisateurs. Je pense que si nous finissons à temps les autres pages prévues, nous pouvons nous attaquer à cette page. Penses-tu que c'est une priorité?
