### ISSUE TITLE
Problèmes lancement serveur

### ISSUE THREAD

**Issue by vasaura** [Chartes-TNAH/dico-proso#30]
J'ai commencé la création de mes pages et des routes et j'ai constaté plusieurs problèmes au lancement du serveur. Les erreurs sont arrivées successivement, donc j'ai réussi à régler certains d'entre eux, mais sur d'autres je bloque complétément. 
Voici les fichiers sur lesquels je suis intervenue: 

- dans le fichier "constantes.py", il y avait la partie tirée de l'exemple 18 de l'application gazetteer que j'ai corrigé comme suit: 
```py
SQLALCHEMY_DATABASE_URI = 'mysql://hoozhoo_user:password@localhost/hoozhoo'
```
J'ai fait pointer la config de test et de production sur notre seule base. En même temps, nous n'avons pas de db.sqlite. En faisant ce changement, nous n'avons plus d'erreurs sur la config. 

- dans le fichier données.py j'ai corrigé une typo et j'ai rajouté un db.relationship aux classes Authorship_link et Link 

- dans le fichier "conteneur.html", j'ai fermé deux balises {% endif %} et {% endwith %}
(En plus, j'ai constaté que tant que la page accueil n'est pas créé, la page conteneur provoque toujours des erreurs, donc il vaut mieux exécuter le code sans {% extends "conteneur.html" %} de la page html )

Malgré ces corrections, l'application continue de planter, mais maintenant uniquement sur la base de données. Il semble que sql alchemy a un problème avec "double foreign key on the same table". Je ne ne sais pas comme remédier ce problème. Voici le message d'erreur précis:
"Could not determine join condition between parent/child tables on relationship Person.link_pers1 - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table."

**Comment by alix-tz** [comment]
Si j'ai bien suivi, il reste juste un problème au niveau du modèle de données, c'est ça ?

**Comment by vasaura** [comment]
Oui, c'est ça

**Comment by alix-tz** [comment]
Bon Aurélia, après une discussion fort instructive, après que tu t'es rendue compte que le serveur ne se lançait pas si on met la partie "test" de constantes.py en commentaire :  
- on doit s'assurer que dans app.py et dans run.py, c'est "production" qui est donné pour `app = config_app("production")` et `def config_app(config_name="production"):`.  

Il faudra sûrement qu'on revienne sur cette partie du code au moment de mettre en place la partie "test".

**Comment by vasaura** [comment]
Serveur lancé: issue fermée 👍

**Comment by alix-tz** [comment]
On peut fermer cette issue, car le problème est résolu. Il faut juste garder en tête qu'il faudra y revenir pour la phase de test.
