### ISSUE TITLE
Méthode de travail sur le fichier generic.py

### ISSUE THREAD

**Issue by vasaura** [Chartes-TNAH/dico-proso#32]
En essayant de faire fonctionner les routes dont je suis en charge, j'ai réalisé que le fichier generic.py qui va regrouper toutes nos routes est lié à toutes les autres pages de notre application par l'import des packages et des modules. Le fait de travailler sur une route_MonNom.py (comme convenu au début) perturbe cette configuration, car route_MonNom.py n'est pas appelé dans les autres pages. Le fait de refaire le circuit de renvoi à la main nous expose à des grandes risques de confusion lors de l'assemblage final. 

J'ai réalisé les testes à partir du fichier "generic.py" (mon issue  #30). Du coup j'ai rajouté ce fichier avec une route simple sur mon dernier (PR  #31 ). Si cela vous dérange, je vais tout supprimer et nous revenons à notre idée du début. 
Mais ma proposition est de travailler ensemble sur le fichier generic.py (celui qui regroupe toutes les routes). S'il y a des conflits, nous allons les corriger à la main. Il me semble que GIT nous offre la possibilité de travailler sur le même fichier. Il a été crée aussi pour ça, non?

**Comment by alix-tz** [comment]
Pour tester la route sur ton poste de travail, tu peux travailler dans generic.py. Ma proposition c'était de pusher dans un fichier à part qui s'appelerait route_prenom.py, avant de rassembler au fur et à mesure les routes écrites dans generic.py.  
On peut aussi toutes travailler directement dans generic.py. Le tout c'est de vérifier qu'on a bien la dernière version du fichier au moment de faire la PR. Ou bien de faire une PR sur une PR pour anticiper autant que possible les conflits. Sinon, on les règlera à la main : ça ne sera qu'une question de copier-coller un bloc, après tout !

En tout cas, pas de problème pour que tu aies inclus ta route dans ta dernière PR. :)

**Comment by alix-tz** [comment]
Finalement, on travaille directement sur generic.py, et on gère à la main les conflits, tout en essayant de les limiter en coordonnant notre travail.

**Comment by lduflos** [comment]
Ok, normalement si on fait attention à bien mettre le repository à jour avant d'envoyer notre code ça devrait réduire les conflits
