### ISSUE TITLE
Intégration de l'ontologie SNAP

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/dico-proso#35]
Comme prévu, j'ai "récupéré" à la main l'ensemble des classes de relations que propose l'ontologie SNAP :  [ici](http://snap.dighum.kcl.ac.uk/owl/snap.owl) et [là](http://snap.dighum.kcl.ac.uk/ontology/).  

J'ai d'emblée eu l'impression qu'il fallait qu'on rationalise ces relations, et j'ai utilisé [la modélisation en graphe proposée par SNAP](http://snapdrgn.net/ontology) pour comprendre comment s'articulent toutes les classes de relations. 
![snapontograf](https://user-images.githubusercontent.com/33317799/37567804-40469daa-2acc-11e8-9bd3-5751175f4561.png)  

Grâce à ce graphe, j'ai réduit le nombre de types de relation qui seraient disponibles pour l'utilisateur à *26*. Je pense que la meilleure manière d'optimiser l'ontologie, c'est en différenciant les "degrés"/niveaux associés à la relation dans la table `relation_type` en ajoutant des colonnes supplémentaires.  

Quand on regarde le graphe, le type "BrotherOf", dépend de "SiblingOf", qui dépend de "HereditaryFamilyOf", qui dépend de "Bond". Ce sont des degrés de relation qui seront intéressants à exporter dans notre API JSON-LD, mais dont on n'a pas nécessairement besoin dans notre base de relation entre les personnes. En rationalisant ces relations, j'ai aboutit à 4 degré supplémentaires maximum. On aurait donc besoin d'ajouter 4 colonnes à notre table.   

Pour clarifier tout ça, j'ai créé un tableau qui correspond à ce à quoi ressemblerait notre table `relation_type`. J'aimerais savoir ce que vous en pensez. 

Voici ce que ça donnerait : 
![table_relation_type_maj](https://user-images.githubusercontent.com/33317799/37570795-a07b0ada-2af4-11e8-8c7d-9e98284d803e.png)

---

J'en profite pour préciser : les couleurs correspondent à des groupes logiques de relation (dont je me servirais sur la page de création de lien), et je signale que l'ontologie SNAP contient une faute de frappe : "emnity" n'existe pas en anglais, et en toute logique, compte tenu de son articulation avec "FriendshipFor", ce type devrait s'écrire "EnmityFor".

**Comment by vasaura** [comment]
Je trouve que c'est une très bonne idée cette nouvelle modélisation de l'ontologie. Les relations entre les personnes sont mieux structurées. Si tout le monde valide cette structure, je me charge de refaire le script mysql de données et le script d'insertion à partir des données insérées par @alix-tz dans le fichier csv.

**Comment by lduflos** [comment]
Merci Alix.
Je valide et je rejoins Aurélia : les niveaux permettent une meilleure compréhension et il sera bien de les obtenir lors d'un export de l'API.

**Comment by vasaura** [comment]
Dans ce cas, j'envoie le nouveau script de la base de donnée, le script de données pour la table type_relation et le nouveau diagramme. 
Vous pouvez exécuter dans workbench les deux scripts pour les mettre à jour.

**Comment by vasaura** [comment]
j'ai une question. A partir de cette ontologie, comment faudrait-il définir la relation entre des époux? je n'ai pas vu ce type de relation. Le seul truc qui se rapproche est #SeriousIntimateRelationshipWith

**Comment by alix-tz** [comment]
Oui c'est bien comme ça que je le comprends : casualintimaterelationshipwith serait par opposition en quelque sorte une relation hors mariage.

**Comment by vasaura** [comment]
d'accord. Merci. Clairement notre application est destinée à des utilisateurs qui connaissent SNAP
