### ISSUE TITLE
Page "index"

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/dico-proso#39]
Dans #30 , @vasaura , tu as signalé que tu avais des problèmes pour lancer sur le serveur la page notice que tu as créée. Tu as fait une branche spécifique sur notre repository : `routeAurelia` pour que je puisse tester si je rencontrais le même problème sur mon poste, et c'est bien le cas. 

Le message d'erreur initial était : 
> sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between 
> parent/child tables on relationship Person.link_pers1 - there are multiple foreign key paths 
> linking the tables. Specify the 'foreign_keys' argument, providing a list of those columns which 
> should be counted as containing a foreign key reference to the parent table.

Après une petite recherche, je suis tombée sur la solution suivante : 
- http://docs.sqlalchemy.org/en/latest/orm/join_conditions.html

Il s'agirait donc dans les 2 tables dans lesquelles la jointure est faite 2 fois sur une même autre table, c'est-à-dire dans les tables `Person` et les tables `Link`, de remplacer "back_populates" par "foreign_keys". 

C'est ce que j'ai fait, d'abord pour la table "Person" seulement, mais j'ai eu le même message d'erreur que précédemment, portant sur "Link". J'ai donc fait la même modification sur "Link".

Cela donne : 
```
class Person(db.Model):
    ...
    link_pers1 = db.relationship("Link", foreign_keys="person1")
    link_pers2 =  db.relationship("Link", foreign_keys="person2")

class Link(db.Model):
    ...
    person1 = db.relationship("Person", foreign_keys="link_pers1")
    person2 = db.relationship("Person", foreign_keys="link_pers2")
```

Malheureusement, la page ne fonctionne toujours pas car j'ai le message d'erreur suivant : 
> sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|Link|link, expression 
> 'link_pers1' failed to locate a name ("name 'link_pers1' is not defined"). If this is a class name,
> consider adding this relationship() to the <class 'hoozhoo.modeles.donnees.Link'> class after 
> both dependent classes have been defined.

Je continue de chercher une solution, mais il me semble que cette fois l'erreur est aussi induite par la requête. Peut-être que c'est lié au fait qu'à ce stade de mon test, aucune relation n'a été créée.

**Comment by vasaura** [comment]
Merci beaucoup pour ton travail et pour les pistes que tu as lancées. Je vais regarder de mon coté, je vais essayer de faire des testes à partir de tes suggestions: créer quelques link voir si cela nous aide.

**Comment by vasaura** [comment]
J'ai regardé aussi les exemples proposés et j'en ai testé une partie. 
en effet, il faut remplacer backpopulates par foreign_keys, mais cela uniquement dans la classe qui contient les FK, donc, dans notre cas, Link. 
Aussi, la valeur de la foreign_keys est représentée par l'attribut de la classe qui contient la FK. Donc, dans notre cas cela donnerait:
```py
class Link(db.Model):
..........
person1 = db.relationship("Person", foreign_keys=[link_person1_id])
person2 = db.relationship("Person", foreign_keys=[link_person2_id])
```
En revanche, cette procédure ne marche pas pour la class Personn (car elle n'a pas de Fk). 
Je crois qu'il faut la définir autrement, mais je ne sais pas comment.

**Comment by vasaura** [comment]
Je viens de tester pour la classe Personn, l'exemple proposé au chapitre "Specifying Alternate Join Conditions" sur le site signalé par @alix-tz. 
si on utilise primaryjoin ça a l'air de marcher. Plus d'erreurs. Je ne sais pas quelles peuvent être les implications de cette modélisation, mais en tout cas, à ce stade, je n'ai plus d'erreurs.
```py
class Personn (db.Model):
link_pers1 = db.relationship("Link", primaryjoin="Person.person_id==Link.link_person1_id")
link_pers2 = db.relationship("Link", primaryjoin="Person.person_id==Link.link_person2_id")
```
Ca ressemble à une déclaration de jointure comme dans mysql
On verra au cours de nos testes si cette configuration tient la route.

**Comment by alix-tz** [comment]
Le problème est résolu !
