### ISSUE TITLE
Data model SQL

### ISSUE THREAD

**Issue by vasaura** [Chartes-TNAH/dico-proso#4]
J'ai réalisé un script de model pour notre base de données. Je me suis inspiré du modèle de gazetteer (fichier datamodel.sql). 
Par rapport au schéma que nous avons débattu ensemble, j'ai apporté les modifications suivantes:
- je n'ai pas fait de base séparée pour le genre, car j'ai vu qu'il existe en sql une manière de déclarer des champs avec des valeurs par défaut (H, F, ..) avec ENUM.
- J'ai créé deux bases de type authorship, une qui lie le user à la table personne et une qui le user à la table type de relation. C'est parce que je craignais qu'on allait se compliquer la vie avec une table qui lie 3 tables. J'ai l'impression que c'est plus simple comme ça. 

Il reste une erreur de syntaxe dans les droits accordés aux utilisateurs ("GRANT EXECUTE ON ROUTINE `hoozhoo`.* TO 'hoozhoo_user';"). Je ne comprends pas pourquoi. D'ailleurs le modèle de gazeetter contient la même erreur de syntaxe. Malgré cet erreur, on arrive à créer la base sans problème, donc vous pouvez executer le script depuis workbench (je vais préciser dans requirements.txt. comment procéder).

Pour le typage de données, j'ai eu un seul doute: sur les dates de naissance et mort (apparemment, mysql accepte le format "date" à partir de 1001 à 9999. Mais nous allons insérer des données d'avant 1001. Du coup, j'ai mis le typage en varchar.) Dites-moi ce que vous en pensez. Peut-être j'ai mal compris.

**Comment by alix-tz** [comment]
Pour le modèle général, c'est conforme à ce qu'on a vu ensemble. 
Il me semble que ça ne pose pas de problème de ne pas faire une table pour le genre (mais pourquoi ne pas écrire "homme" et "femme" en toutes lettres si on écrit "inconnu" en entier ?).  

Concernant le code lui-même, je manque d'expérience en MySQL pour comprendre la partie sur les jointures côté "création", j'aurais du mal à te signaler s'il y a une erreur.  

Un ligne m'intrigue tout de même, la 143, où il est écrit : `+ DROP USER hoozhoo_user;`  
-> pourquoi ?

Qu'est-ce qui te signale la ligne `GRANT EXECUTE ON ROUTINE hoozhoo.* TO 'hoozhoo_user';` comme une erreur ?  

Enfin, y a-t-il un calcul derrière le choix d'une limite à 10 caractères pour le varchar des dates ? Si oui, as-tu aussi compté la présence du "-" devant la date si elle est antérieure à l'an 0 ? 

Merci pour tout ce travail en tout cas !

**Comment by lduflos** [comment]
Avec @eglantinecharmetant, nous avons bosser la modélisation de la base d'après le modèle sql de @vasaura 
Voici un aperçu de notre base, nous avons tout de même recontré des problèmes lors de la saisi des champs dans workbench (FK table authorship et relationship). Je push plus tard le modèle sur le repo pour que chacune puisse l'avoir.
![db_model](https://user-images.githubusercontent.com/33370304/36900736-ca852d1a-1e24-11e8-83fe-02d07081f7c9.png)

Concernant, le code sql effectivement je ne comprends pas très bien les dernières lignes comme @alix-tz

**Comment by eglantinecharmetant** [comment]
Par contre dans la table user, il me semble que VARCHAR (45) et VARCHAR(100) pour le user_login et le user_password c'est peut être un peu beaucoup, qu'en pensez-vous?

**Comment by alix-tz** [comment]
Et je fais aussi remarquer que selon moi, la table "relationship" (dont le nom n'est pas très explicite...) devrait lier "user" et " lienPersonnes" ; et ne pas toucher "typeRelation" (c'est une table dont le contenu est standardisé et l'user n'aura pas à intervenir dessus).

**Comment by alix-tz** [comment]
Sinon, franchement c'est du bon boulot, ça aide vraiment à la lisibilité de la table ! :+1:

**Comment by vasaura** [comment]
Je vais prendre en compte vos remarques. Je vais modifier la base en conséquences. @alix-tz t'as raison sur le lien entre la table relationship et type relation. 
Pour éviter d'autre confusion, je vais passer tous les  noms des tables et attributs en anglais. 

Pour l'histoire de drop user (ligne la 143), j'ai fait un copier-coller du gazetteer. Je vais simplifier comme ceci: 
````
DROP USER IF EXISTS hoozhoo_user;
CREATE USER 'hoozhoo_user' IDENTIFIED BY 'password';
GRANT INSERT, SELECT, UPDATE, DELETE ON `hoozhoo`.* TO 'hoozhoo_user';
````
Pour le champ "date", j'avais pris en compte le format YYYY/MM/JJ, d'où le varchar (10). J'ai pas pris en considération les dates avant JC. A voir ensemble comment on gère ces années. On rajoute un + ou - devant la date et donc passer à varchar(11)? 

Il me semble que certaines tables des diagrammes que vous avez générés n'ont plus de primary key: user et lienpersonne. C'est peut-être la raison des erreurs dont parlait @lduflos.

**Comment by vasaura** [comment]
J'ai fais un pull request avec les modifications sur la base, y compris un diagramme global. Est-ce que c'est mieux?

**Comment by lduflos** [comment]
@vasaura Effectivement, je n'avais pas vu. Toutes mes excuses, j'ai du oublier de les cocher lors de la réalisation du diagramme EER... Je vais aller voir ta PR, merci

**Comment by alix-tz** [comment]
tu as résolu ce problème avec #106
