### ISSUE TITLE
Fonctionnement des fichiers conteneur

### ISSUE THREAD

**Issue by lduflos** [Chartes-TNAH/dico-proso#43]
#41 

Alors, suite à ma PR désormais nous avons 2 fichiers conteneurs : 
- le fichier "conteneur_complet" correspond au conteneur à l'état final. Donc il suffit de s'en inspirer lorsque nous avons besoin de faire des modifications dans le fichier test "conteneur"
- le fichier "conteneur" correspond désormais au fichier test donc lorsque nous avons de nouvelles pages de créées il suffit de faire les modifications en ajoutant les urls des pages

**Comment by lduflos** [comment]
A noter, lorsque vous déclarer vos `url_for` il faut utiliser le nom du fichier html de la page concernée.
Ex : `<a href="{{url_for("about")}}" class="text-secondary">A propos</a>`

**Comment by vasaura** [comment]
C'est parfait. Merci beaucoup pour ces consignes. 👍

**Comment by eglantinecharmetant** [comment]
Merci Léa! :)

**Comment by lduflos** [comment]
Je suis actuellement en train de faire la page "création personne" et je m'aperçois que le "footer" du conteneur est fixe et du coup ça ne m'affiche pas ma page en entier. Et, le header quand à lui disparait lorsqu'on descend... Il va donc falloir penser à modifier cela
