### ISSUE TITLE
Pages Index+Notice

### ISSUE THREAD

**Issue by vasaura** [Chartes-TNAH/dico-proso#52]
J'ai créé les fonctionnalités de base pour la page index et notice. 
Il reste la pagination pour l'index et les boutons vers les pages "modification" et "créer de liens", ainsi qu'une révision de la partie html, car à ce stade c'est une imitation du gazetteer.
Par rapport au mockup, il y a la traduction en français des champs et la disparition du champs "also know as" (inexistant encore dans notre modèle de données; à voir si on le fait évoluer)
Je précise qu'à mon sens il est important d'afficher "nom, prénom, surnom" ensemble, car sans cela l'identité des personnes est ambigue pour l'utilisateur. 
Il faut revoir l'intitulé de certains champs en collaboration avec @lduflos car les champs du formulaire de saisie sont les mêmes.
Pout l'ID externe, je propose de prendre uniquement IDWikidata et de le mentionner comme tel, car il est difficile de faire varier les id. (à discuter...)

**Comment by vasaura** [comment]
Mise à jour de la page Notice avec les éléments suivants :
des liens url pour les personnes liées à la personne principale de la notice 
un lien url pour l'index dans conteneur 
2 boutons un pour modifier (qui sera activé au moment de la création du formulaire de modification) et un qui renvoie vers "créer lien".

**Comment by alix-tz** [comment]
Je confirme que tout fonctionne pour cette partie de l'application.

**Comment by vasaura** [comment]
rappel: il faut rajouter un contrôle pour le cas oû on insère un id qui n'existe pas, car actuellement on a un AttributErreur

**Comment by alix-tz** [comment]
Tu as résolu ce problème avec la #113
