### ISSUE TITLE
Page création personne

### ISSUE THREAD

**Issue by lduflos** [Chartes-TNAH/dico-proso#58]
Je viens de pusher ma branche "creer_personne" sur le repository pour que vous puissiez y avoir accès. Il faut encore que je travaille sur les tests. Pour le moment, ce qui fonctionne : 
- l'obligation de remplir au moins un des champs (nom ou prenom ou surnom) ainsi que la description
- intégration des informations dans la base de données
- côté html j'ai résolu le problème pour le genre : un seul choix est désormais possible
Je vais continuer à améliorer ça et je suis preneuse si jamais vous avez des remarques concernant mon code ;)

**Comment by alix-tz** [comment]
Merci Léa, par contre je ne vois pas ta branche sur le repository. Est-ce que par hasard tu aurais uniquement pushé sur ton fork ?

**Comment by alix-tz** [comment]
``` python
        if not (nom or prenom or surnom): 
                 errors.append("Un des trois champs (nom, prénom, surnom) est obligatoire")
```

Je pense que cette partie du test ne fonctionne pas encore de manière optimale : si les 3 champs sont remplis, cela crée une ereur.  
Pour moi la requête signifie "s'il n'y a rien, soit dans nom, soit dans prénom, soit dans surnom, alors ajoute une erreur". Et j'aurais tendance à penser que ça a plutôt l'effet inverse : ça ferait une erreur que si les 3 champs sont remplis... Mais ça a pas l'air de fonctionner comme ça, alors je suis perplexe...

**Comment by lduflos** [comment]
Oui pardon, la branche est sur mon fork... Je l'ai pas pushé où il fallait :innocent:

**Comment by vasaura** [comment]
Pour moi c'est logique 
```py
if not (nom or prenom or surnom).
```
car c'est la négation de "soit nom, soit prenom, soit surnom=True". C'est comme si on disait 
if (nom or prenom or surnom).
     OK
Sinon 
    erreur
@alix-tz je ne comprends pas ce que tu veux dire par 'si les 3 champs sont remplis, cela crée une erreur.' Je ne pas d'erreur en faisant le test
Mais dans tout les cas, le code marche, donc Léa, tu peux faire ta PR pour qu'on mette à jour notre appli?

**Comment by alix-tz** [comment]
Ok Aurélia, merci !
Par contre j'ai bien eu une erreur dans mon test (finalement peut être pas lié aux 3 champs). L'erreur était générée au moment de la dernière partie du code, au moment du try/except.  
Je vais refaire des tests pour voir si je retrouver l'erreur.

**Comment by vasaura** [comment]
J'ai une autre remarque. C'est au sujet de l'ID externe. Dans le formulaire, il est indiqué de choisir le type d'ID: VIAF, Wikidata ou IDref. Dans notre modèle sql, nous n'avons pas prévu de distinguer les trois types, donc tous les id insérés par les utilisateurs vont se retrouver en vrac dans la même colonne. Comment pensez-vous qu'il vaut mieux procéder pour régler cet aspect? Je vous propose de n'utiliser que l'id wikidata pour le moment, même si ce n'est pas idéal.

**Comment by lduflos** [comment]
Pense-bête : faire le lien dans la nav-bar

**Comment by vasaura** [comment]
Voici mes propositions concernant les vérification que nous devons faire pour la page création personne: 
- vérifier que le genre est renseigné.

- vérifier qu'une personne n'a pas été déjà insérée. Pour l'instant, la vérification se fait sur nom, prénom et surnom, mais il se peut qu'une personne ait le même nom ou que l'utilisateur insère le nom anglais de la même personne. Je propose donc de rendre obligatoire l'ID Wikidata et de considérer qu'une personne est unique à partir de cet ID et non pas du nom, prénom et surnom. Qu'en pensez-vous?

**Comment by alix-tz** [comment]
Alors pour reprendre mes éléments de réponse : 
- je suis du même avis pour le genre
- si une personne veut utiliser cette application pour travailler sur des personnes qui n'ont pas d'ID Wikidata, elle va perdre la possibilité de contrôler que la personne créée n'existe pas déjà. Mais c'est vrai que l'ID wikidata est unique et est une bonne base pour une détection rapide et simple des doublons.

**Comment by lduflos** [comment]
On peut peut être commencé par rendre obligatoire le wikidata ID et améliorer la chose par la suite, parce que c'est vrai qu'en vérifiant uniquement sur le nom, prenom ou surnom c'est très complexe à gérer!

**Comment by lduflos** [comment]
Pour les tests, je prends vos remarques en compte. Comme certaines avaient besoin de ma page, j'ai pushé mais je n'avais pas fini de travailler sur le code mais ça sera fait d'ici mercredi

**Comment by lduflos** [comment]
J'informe que ma page ne fonctionne plus, comme je le présentais l'ajout des 4 champs supplémentaires provoque des erreurs. Je me charge de faire les rectifications ainsi que les améliorations nécessaire demain !

**Comment by lduflos** [comment]
Je viens de pusher mes modifications (branche maj_creerpersonne) : 
- navbar : correction de l'onglet 'contribuer' en 'créer une personne' (harmonisation avec ce qu'avait fait Alix) + ajout du lien url (changement de url 'creer_personne' en 'creer-personne')
- ajout des 4 champs dans le formulaire de création personne : **attention!**, comme nous n'avons pas défini les dénominations de ces champs pour le moment ce sont les noms provisoires 
#61 + suppression dans les *placeholder* des mentions JJ-MM-YYYY pour les dates
- màj de la méthode statique : 
 - nom, prenom ou surnom obligatoire
 - genre et description obligatoires
 - wikidata id obligatoire avec vérification qu'il commence bien par un Q et max 12 caractères
 - vérification du nombre de caractères (//SQL)

**Comment by vasaura** [comment]
@lduflos Il me semble qu'il y a un bug au niveau de la création personne, car j'arrive à créer une personne avec le même identifiant Wikidata. Je pensais avoir vérifié et testé cet aspect, mais aujourd'hui je constate qu'on a cette "erreur".

**Comment by lduflos** [comment]
```python
# vérifier si la personne existe
 personne = Person.query.filter(db.and_(Person.person_name == nom, Person.person_firstname == prenom,
                                               Person.person_nickname == surnom)).count()
        if personne > 0:
errors.append("La personne est déjà inscrite dans la base de données")
```

Effectivement, je suis pas sûre de l'avoir pris en compte. Du coup, je pense qu'il suffit d'ajouter la vérification par l'id extérieur : 
` personne = Person.query.filter(db.and_(Person.person_name == nom, Person.person_firstname == prenom,
                                               Person.person_nickname == surnom, Person.external_id == id_externes)).count()`

Je m'occupe de cet ajout ce soir, merci Aurélia pour l'info
