### ISSUE TITLE
Compléter les informations pour Person

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/dico-proso#61]
Je vous ai signalé en fin de semaine que, n'ayant pas été là lorsque la décision avait été prise, je ne comprenais pas pourquoi nous n'avions pas conservé les éléments "nationalité", "nom dans la langue maternelle", "langues/langages parlés, écrits, signés" et "occupation".  
Ils sont utiles pour l'extraction en JSON et font à mon sens partie de la consigne. On peut les ajouter sous à la forme de nouvelles colonnes dans "Person", sans avoir à créer des tables exprès.  
Il me semble aussi que c'est le moment où jamais pour les ajouter.

**Comment by vasaura** [comment]
D'accord. Tu peux refaire le modèle de données?

**Comment by alix-tz** [comment]
Ok !

aucun des champs n'est "not null", ja ?

**Comment by vasaura** [comment]
on a deux champs not null: description et genre

**Comment by lduflos** [comment]
Du coup si je comprends bien vous avez ajouté 4 nouveaux champs ?
Champs en question que je dois ajouter dans le formulaire "creation personne" ?

**Comment by alix-tz** [comment]
Oui les champs sont les suivants : 
- person_country : pour "country of citizenship" (nationalité ?)
- person_language : pour langues parlés/écrits ou signées
- person_occupations
- person_nativename : pour le nom dans la langue maternelle (un seul champ pour tout le nom). 

Il faudra les ajouter, mais pour le moment ça n'empêchera pas ton formulaire de fonctionner vu que ces nouvelles colonnes peuvent être vides.  

Ca te convient ?

**Comment by vasaura** [comment]
Etes-vous d'accord de procéder à cette modification une fois qu'on a bien avancé sur les  fonctionnalités principales de notre application? C'est à dire qu'il faut d'abord faire fonctionner toutes les pages, s'assurer des contrôles de erreurs, etc.

**Comment by alix-tz** [comment]
Si tu parles de modifier les pages, ok  

Par contre je ne vois pas l'intérêt d'attendre que tout ça fonctionne pour mettre à jour la base de données...

**Comment by lduflos** [comment]
Je viens de me pencher sur la question, effectivement je trouve qu'il est pertinent de mettre la nationnalité, la fonction et le nom original mais je ne vois pas l'intérêt de garder lle champ "langues parlées/écrites...". Mais peut être que je passe à côté de qq chose
