### ISSUE TITLE
Test - Jeux de données

### ISSUE THREAD

**Issue by eglantinecharmetant** [Chartes-TNAH/dico-proso#7]
avec @lduflos  nous avons effectué la généalogie des Héraclides pour constituer le jeu de données qui servira de test pour la db. 
![20180302_151047](https://user-images.githubusercontent.com/33157165/36903007-a07f16ea-1e2c-11e8-8d48-51b0a478449c.jpg)

**Comment by lduflos** [comment]
Comme l'a fait remarquer @alix-tz , dans le jeu de données test il faut penser à faire des modifications ou des ajouts pour qu'il y ait la variable 'inconnu' qui apparaisse pour le 'genre'
