### ISSUE TITLE
Modification notice personne

### ISSUE THREAD

**Issue by vasaura** [Chartes-TNAH/dico-proso#73]
Je voulais signaler quelques bugs/insuffisances dans la page modification personnes. 

J'ai rajouter une fonctionnalité de contrôle pour afficher "Aucune modification n'a été réalisée" dans le cas où l'utilisateur clique sur le bouton "Modifier" sans faire des modifications, car lorsqu'on cliquait sur "Modifer", on avait toujours le message "Modification réussie". 
Pour cela j'ai du faire un contrôle (dans staticmethod) pour tous les champs. Au niveau du champs "description" (placé dans la balise <textarea>) j'ai eu des soucis car les espaces au début ou à la fin du texte créaient une sorte de différence entre le texte stocké dans base et celui qui apparaissait à l'écran et même si on ne modifiait pas le texte, en cliquant sur "Modifier" on avait le message "Modification réussie". 
Pour remédier j'ai trouvé la fonction strip() qui supprime les espaces avant et après et cela ne crée plus de différences, donc si le texte n'est pas modifié, alors on a le message "la page n'a pas été modifiée". 

Maintenant, j'ai réalisé le piège de ce strip(), car si l'on veut rajouter ou supprimer des espaces au début ou à la fin du texte dans description, cela n'est pas pris en considération et on a toujours le texte "Aucune modification n'a été réalisée" et en effet la page n'est pas modifiée. 

Donc, voila, si vous avez des idées.... D'autre part, je me demande pourquoi on a des espaces au début du texte de description. Moi, je n'en rajoute pas, mais plus je fais des testes, plus il y en a. Je continuerai à explorer la question

**Comment by alix-tz** [comment]
Concernant ton test pour "aucune modification n'a été faite", j'ai voulu mettre aussi ce contrôle pour modification de liens, mais je ne l'ai finalement pas gardé parce que j'ai pensé que c'est pas si grave de re-enregistrer une notice qui n'a pas été modifiée...  
En tant qu'utilisateur, ça m'arrive de cliquer sur une fonction pour modifier quelque chose, et puis de me rendre compte que finalement j'ai rien à modifier et d'enregistrer plutôt que de revenir en arrière pour "annuler".

**Comment by vasaura** [comment]
D'accord. J'ai éliminé provisoirement ce contrôle histoire de voir si ce problème d'espace disparait et en fait, non. Si je modifie la notice, peu importe à quel niveau, il y a un espace qui se rajoute en début du texte de description. On verra plus tard comment remédier.

**Comment by alix-tz** [comment]
Effectivement, un espace avant le texte est ajouté dans le champ description du formulaire quand on veut modifier la notice, mais si je modifie un peu le texte dans ce champ, sans pour autant enlever cet espace, quand j'enregistre les modifications et que je retourne sur la notice, l'espace n'est plus là.  
Inutile de t'embêter avec ça pour le moment !

**Comment by vasaura** [comment]
En travaillant sur la mise à jour de la page de modification de la notice, je me suis aperçue que j'avais laissé un espace entre la balise textarea et le code qui renvoyait la description. L'erreur vient de là, donc j'ai corrigé et tout va bien.
