### ISSUE TITLE
Json_LD

### ISSUE THREAD

**Issue by vasaura** [Chartes-TNAH/dico-proso#97]
J'ouvre une nouvelle issue pour qu'on puisse échanger au sujet de la modélisation des données en Json-LD. Le sujet est lié à la question d'api (issue #85 ), mais il a ses particularités, d'où une issue dédiée. 
J'ai fait une première proposition de modélisation sur la branche jsonLD. Je ne suis pas sure d'avoir bien compris comme ça marche, mais bon, disons que le jsonLD que j'ai réalisé est correct du pdv de la structure, car on a une visualisation intéressante ici https://json-ld.org/playground/. 
Je me suis inspiré des cours de Gautier Poupeau et du modèle qu'il nous a présenté en Json-LD. En cherchant les bons préfixes, je me suis aperçue que notre ontologie foaf est loin d'être complète. 
C'est pourquoi, j'ai proposé de récupérer les attributs proposés pour la classe Personne dans l'ontologie http://schema.org/Person qui est beaucoup plus adaptée à nos besoins. 
J'ai marqué dans les commentaires du code les éléments à problèmes (par exemple les parties où nous avons du foaf). Mais aussi je crois que nous devons utiliser uniquement l'attribut name et rajouter les 3 valeurs de la base: nom, prénom, surnom)
Il reste à explorer davantage le concept de "contexte" dans JsonLD, car pour l'instant il ne contient que la déclaration des préfixes.
Mais, tout ça est fragile, donc à nous d'éclaircir la question.

**Comment by vasaura** [comment]
je rebondit sur les commentaires de @alix-tz PR #96  concernant le json LD et la pérennité des identifiants. Je me demande si pour la pérennité, nous ne devions pas faire des demandes à des établissement dédiés pour avoir des URI respectant une certaine norme... Peut-être ici nous restons sur un exercice de principe? j'ai une compréhension limitée du sujet. On doit encore explorer.

**Comment by vasaura** [comment]
Oui, j'y ai pensé aussi. Mais je me suis dit que nous avons créé de nouvelles entités avec d'autres attributs que dans wikidata et des relations qui peuvent  être potentiellement différentes. Donc, nous avons notre propre personne unique, qui a un url unique sur notre site. Peut-être qu'il faut rajouter l'url de notre site dans le @context.

**Comment by alix-tz** [comment]
Le problème c'est que selon les utilisateurs de notre application, en fonction des personnes et des contenus qu'ils auront mis dans leur base, un même identifiant sera partagé par plusieurs personnes différentes.  
Par contre, peut-être que je me trompe, mais je crois pas qu'on soit privé d'utiliser des identifiants extérieurs, ils n'ont sûrement pas à correspondre à l'intégralité des informations qu'on a par ailleurs dans notre application, surtout vu qu'on est dans le contexte d'un fichier json.  
Continuons à regarder tout ça...

**Comment by vasaura** [comment]
je ne comprends pas pourquoi un même identifiant sera partagé par plusieurs personnes. Si on a une seule base,  un seul serveur, on aura un seul identifiant, non? 
Je ne pense pas non plus être privé d'utiliser des id extérieurs; d'ailleurs, t'as vu, j'ai mis l'url wikidata dans notre jsonLD à partir de l'id wikidata, et pas seulement l'id. 
Mais je me demandais sur le principe, en quoi consiste un @id qui respecte les normes du graphe dans jsonLd

**Comment by alix-tz** [comment]
Mais notre application n'est pas en ligne : elle est utilisée localement. Du coup toi et moi on n'a pas nécessairement les mêmes identifiants passé les personnes ajoutées grâce au sample.

**Comment by vasaura** [comment]
En effet, nous sommes en production maintenant, mais dans l'absolu notre application est censée être sur le web, à la disposition de tous, donc fournir des pages uniques pour chaque personne.

**Comment by alix-tz** [comment]
@lduflos @eglantinecharmetant @Verronmere , pourriez-vous aussi participer à la reflexion et jeter un oeil aux PR ?

**Comment by vasaura** [comment]
Etant donné que le délai a été repoussé et qu'on a les devoirs tei et omeka à rendre en fin de semaine, on a un peu de marge pour la réflexion sur jsonld

**Comment by alix-tz** [comment]
Ca n'empêche pas qu'on peut être plusieurs à y réfléchir.

**Comment by lduflos** [comment]
Je ne suis pas encore à l'aise avec le JsonLD pour pouvoir donner mon avis, mais je continue à me documenter et reviens vers vous d'ici la fin de la semaine

**Comment by alix-tz** [comment]
Aurelia tu as dit à un moment que tu voyais mal comment on pouvait utiliser la partie "contexte" du JSON-LD.  

Après lecture de la [documentation à ce sujet](https://json-ld.org/spec/latest/json-ld/#the-context), et vu ce que nous extrayons pour le moment dans l'api, je pense que notre partie "contexte" est très simple. Le seul "IRI" que nous puissions fournir pour les termes qui sont listés ensuite, c'est pour l'id de la personne. Il me semble qu'on a seulement besoin de : 
``` 
"@context" : {
"id' : "http://localhost:5000/person/1"
},
...
"id": 1,
...
```

Il y a deux options pour exprimer l'iri. Soit en mettant l'adresse entière, mais on ne peut rien mettre d'autre que "localhost:5000/..." vu que l'application n'est pas sur un serveur, et je crois que ce n'est pas très satisfaisant ; soit en utilisant une [iri relative](https://json-ld.org/spec/latest/json-ld/#dfn-relative-iris), ce qui donnerait, mais je ne suis pas sûre à 100%, `"id": "./person/id"`.

**Comment by alix-tz** [comment]
On pourrait ajouter "homepage", comme dans les exemples qui sont fournis, mais je ne vois pas bien à quoi ça servirait...  
Une autre question que je me pose : faut-il que nous changions la langue utilisée pour nos clefs dans Json ?

**Comment by vasaura** [comment]
Est-ce quelqu'un a regardé déjà ma proposition?

**Comment by alix-tz** [comment]
Non, où se trouve-t-elle ?

**Comment by vasaura** [comment]
"J'ai fait une première proposition de modélisation sur la branche jsonLD." Je l'avais dit en ouverture de cette issue

**Comment by alix-tz** [comment]
Ok, désolée, l'information m'avait échappé.

**Comment by alix-tz** [comment]
cf. #105
